<a href="https://colab.research.google.com/github/vyassuyog1/Janta-hack1/blob/BERT/JantaHackLibrary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Data

In [68]:
import pandas as pd
import numpy as np


In [4]:
!unzip '/content/test_8iecVfC.zip'
!unzip '/content/train_tGmol3O.zip'

Archive:  /content/test_8iecVfC.zip
  inflating: test.csv                
Archive:  /content/train_tGmol3O.zip
  inflating: train.csv               


In [5]:
data_train_original=pd.read_csv('/content/train.csv')
data_test_original=pd.read_csv('/content/test.csv')
data_train=data_train_original.copy()
data_train.set_index(['ID'],inplace=True)
data_test=data_test_original.copy()
data_test.set_index(['ID'],inplace=True)
print(data_train.shape,data_test.shape)
data_train

(20972, 8) (8989, 2)


TITLE  ... Quantitative Finance
ID                                                        ...                     
1            Reconstructing Subject-Specific Effect Maps  ...                    0
2                     Rotation Invariance Neural Network  ...                    0
3      Spherical polyharmonics and Poisson kernels fo...  ...                    0
4      A finite element approximation for the stochas...  ...                    0
5      Comparative study of Discrete Wavelet Transfor...  ...                    0
...                                                  ...  ...                  ...
20968  Contemporary machine learning: a guide for pra...  ...                    0
20969  Uniform diamond coatings on WC-Co hard alloy c...  ...                    0
20970  Analysing Soccer Games with Clustering and Con...  ...                    0
20971  On the Efficient Simulation of the Left-Tail o...  ...                    0
20972   Why optional stopping is a problem for Bayesians  ...                    0

[20972 rows x 8 columns]

In [6]:
data_test

TITLE                                           ABSTRACT
ID                                                                                                         
20973  Closed-form Marginal Likelihood in Gamma-Poiss...    We present novel understandings of the Gamma...
20974  Laboratory mid-IR spectra of equilibrated and ...    Meteorites contain minerals from Solar Syste...
20975         Case For Static AMSDU Aggregation in WLANs    Frame aggregation is a mechanism by which mu...
20976  The $Gaia$-ESO Survey: the inner disk intermed...    Milky Way open clusters are very diverse in ...
20977  Witness-Functions versus Interpretation-Functi...    Proving that a cryptographic protocol is cor...
...                                                  ...                                                ...
29957  Supporting mixed-datatype matrix multiplicatio...    We approach the problem of implementing mixe...
29958        An axiomatic basis for Blackwell optimality    In the theory of Markov decision processes (...
29959  GeneVis - An interactive visualization tool fo...    GeneVis is a web-based tool to visualize com...
29960  Quantifying the causal effect of speed cameras...    This paper quantifies the effect of speed ca...
29961                      Cube-magic labelings of grids    We show that the vertices and edges of a $d$...

[8989 rows x 2 columns]

In [7]:
df=pd.concat([data_train,data_test],axis=0)
df

TITLE  ... Quantitative Finance
ID                                                        ...                     
1            Reconstructing Subject-Specific Effect Maps  ...                  0.0
2                     Rotation Invariance Neural Network  ...                  0.0
3      Spherical polyharmonics and Poisson kernels fo...  ...                  0.0
4      A finite element approximation for the stochas...  ...                  0.0
5      Comparative study of Discrete Wavelet Transfor...  ...                  0.0
...                                                  ...  ...                  ...
29957  Supporting mixed-datatype matrix multiplicatio...  ...                  NaN
29958        An axiomatic basis for Blackwell optimality  ...                  NaN
29959  GeneVis - An interactive visualization tool fo...  ...                  NaN
29960  Quantifying the causal effect of speed cameras...  ...                  NaN
29961                      Cube-magic labelings of grids  ...                  NaN

[29961 rows x 8 columns]

In [8]:
df['train']=[1] * len(data_train) + [0]*len(data_test)
df['train']

ID
1        1
2        1
3        1
4        1
5        1
        ..
29957    0
29958    0
29959    0
29960    0
29961    0
Name: train, Length: 29961, dtype: int64

In [9]:
df

TITLE  ... train
ID                                                        ...      
1            Reconstructing Subject-Specific Effect Maps  ...     1
2                     Rotation Invariance Neural Network  ...     1
3      Spherical polyharmonics and Poisson kernels fo...  ...     1
4      A finite element approximation for the stochas...  ...     1
5      Comparative study of Discrete Wavelet Transfor...  ...     1
...                                                  ...  ...   ...
29957  Supporting mixed-datatype matrix multiplicatio...  ...     0
29958        An axiomatic basis for Blackwell optimality  ...     0
29959  GeneVis - An interactive visualization tool fo...  ...     0
29960  Quantifying the causal effect of speed cameras...  ...     0
29961                      Cube-magic labelings of grids  ...     0

[29961 rows x 9 columns]

#Reading data

In [10]:
df.iloc[10]['ABSTRACT'], df.iloc[10]['TITLE']

('  We present a systematic global sensitivity analysis using the Sobol method\nwhich can be utilized to rank the variables that affect two quantity of\ninterests -- pore pressure depletion and stress change -- around a\nhydraulically-fractured horizontal well based on their degree of importance.\nThese variables include rock properties and stimulation design variables. A\nfully-coupled poroelastic hydraulic fracture model is used to account for pore\npressure and stress changes due to production. To ease the computational cost\nof a simulator, we also provide reduced order models (ROMs), which can be used\nto replace the complex numerical model with a rather simple analytical model,\nfor calculating the pore pressure and stresses at different locations around\nhydraulic fractures. The main findings of this research are: (i) mobility,\nproduction pressure, and fracture half-length are the main contributors to the\nchanges in the quantities of interest. The percentage of the contributio

#Y

In [11]:
Y=df[df.train==1].iloc[:,2:-1]
Y

Computer Science  Physics  ...  Quantitative Biology  Quantitative Finance
ID                                ...                                            
1                   1.0      0.0  ...                   0.0                   0.0
2                   1.0      0.0  ...                   0.0                   0.0
3                   0.0      0.0  ...                   0.0                   0.0
4                   0.0      0.0  ...                   0.0                   0.0
5                   1.0      0.0  ...                   0.0                   0.0
...                 ...      ...  ...                   ...                   ...
20968               1.0      1.0  ...                   0.0                   0.0
20969               0.0      1.0  ...                   0.0                   0.0
20970               1.0      0.0  ...                   0.0                   0.0
20971               0.0      0.0  ...                   0.0                   0.0
20972               0.0      0.0  ...                   0.0                   0.0

[20972 rows x 6 columns]

In [101]:
Y=[np.where(i==1) for i in np.asarray(df[df.train==1].iloc[:,2:-1])]
Y

[(array([0]),),
 (array([0]),),
 (array([2]),),
 (array([2]),),
 (array([0, 3]),),
 (array([2]),),
 (array([1]),),
 (array([1]),),
 (array([1]),),
 (array([4]),),
 (array([0]),),
 (array([1]),),
 (array([1]),),
 (array([0]),),
 (array([1]),),
 (array([2]),),
 (array([1]),),
 (array([2]),),
 (array([3]),),
 (array([1]),),
 (array([4]),),
 (array([1, 2]),),
 (array([0]),),
 (array([0]),),
 (array([2]),),
 (array([1]),),
 (array([0]),),
 (array([2]),),
 (array([2, 3]),),
 (array([1, 2]),),
 (array([0, 3]),),
 (array([2]),),
 (array([0]),),
 (array([4]),),
 (array([0]),),
 (array([0, 2]),),
 (array([1]),),
 (array([0]),),
 (array([1]),),
 (array([0]),),
 (array([3]),),
 (array([5]),),
 (array([1]),),
 (array([0, 2]),),
 (array([0]),),
 (array([0]),),
 (array([2]),),
 (array([0, 1]),),
 (array([0]),),
 (array([3]),),
 (array([0, 3]),),
 (array([1]),),
 (array([0]),),
 (array([0]),),
 (array([0]),),
 (array([4]),),
 (array([1]),),
 (array([0]),),
 (array([0, 3]),),
 (array([0]),),
 (array([0

In [102]:
Y=pd.DataFrame(Y,columns=["Category"])
Y["Category"]=[tuple(i) for i  in Y.Category]
Y

Category
0         (0,)
1         (0,)
2         (2,)
3         (2,)
4       (0, 3)
...        ...
20967   (0, 1)
20968     (1,)
20969     (0,)
20970   (2, 3)
20971   (2, 3)

[20972 rows x 1 columns]

In [73]:
target_dict={k:v for v,k in enumerate(Y['Category'].unique())}
target_dict
target_rev_dict={k:v for k,v in enumerate(Y['Category'].unique())}
target_rev_dict

{0: (0,),
 1: (2,),
 2: (0, 3),
 3: (1,),
 4: (4,),
 5: (3,),
 6: (1, 2),
 7: (2, 3),
 8: (0, 2),
 9: (5,),
 10: (0, 1),
 11: (0, 2, 3),
 12: (1, 3),
 13: (0, 1, 3),
 14: (0, 4),
 15: (3, 4),
 16: (3, 5),
 17: (1, 2, 3),
 18: (0, 5),
 19: (4, 5),
 20: (0, 3, 4),
 21: (0, 1, 2),
 22: (0, 3, 5),
 23: (2, 3, 5)}

In [74]:
Y=pd.get_dummies(data=Y,prefix_sep='_')
Y

Category_(0,)  Category_(0, 1)  ...  Category_(4, 5)  Category_(5,)
0                  1                0  ...                0              0
1                  1                0  ...                0              0
2                  0                0  ...                0              0
3                  0                0  ...                0              0
4                  0                0  ...                0              0
...              ...              ...  ...              ...            ...
20967              0                1  ...                0              0
20968              0                0  ...                0              0
20969              1                0  ...                0              0
20970              0                0  ...                0              0
20971              0                0  ...                0              0

[20972 rows x 24 columns]

In [76]:
num_classes=len(target_dict)
num_classes

24

#X

In [12]:
X_train_val=df[df.train==1]["TITLE"] 
X_test=df[df.train==0]["TITLE"] 
print(X_train_val.shape,X_test.shape)

(20972,) (8989,)


In [13]:
max_len=max([len(i) for i in X_train_val])
max_len

239

In [14]:
X_test.iloc[2]

'Case For Static AMSDU Aggregation in WLANs'

#Split data

In [15]:
from sklearn.model_selection import train_test_split
import numpy as np


In [104]:
X_train,X_val,Y_train,Y_val=train_test_split(np.asarray(X_train_val),np.asarray(Y).flatten(),random_state=42,test_size=0.2)
print(X_train.shape,X_val.shape,Y_train.shape,Y_val.shape)

(16777,) (4195,) (16777,) (4195,)


#Using Bert Tokenizer

In [17]:
!pip install transformers

     |████████████████████████████████| 778kB 8.2MB/s 
     |████████████████████████████████| 890kB 22.9MB/s 
     |████████████████████████████████| 3.0MB 17.3MB/s 
     |████████████████████████████████| 1.1MB 54.7MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=08f6b96f6bad4d8669e4a6d5b150ca717b9243cf7376ad2c6e5b0b1470888aba
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [18]:
from transformers import BertTokenizer
from torch.utils.data import TensorDataset
import torch

In [19]:
tokenizer=BertTokenizer.from_pretrained('bert-base-uncased',
                                        do_lower_case=True)                        #uncased- as it is not lowered and 
                                                                                   #it uses pretrained tokens(i.e from_pretrained)

In [77]:
encoded_data_train=tokenizer.batch_encode_plus(X_train ,                       #for train data
                                               add_special_tokens=True,                          # add spl tokens (start , end)
                                               return_attention_mask=True,                        # the actual length of sentence
                                               pad_to_max_length=True,                           #pad till max len(to get same i/p size)
                                               max_length=max_len,
                                                                                            
                                               return_tensors='pt')                             #pt=pyTorch

encoded_data_val=tokenizer.batch_encode_plus(X_val,
                                               add_special_tokens=True,
                                               return_attention_mask=True,
                                               pad_to_max_length=True,
                                               
                                               max_length=max_len,
                                               return_tensors='pt')

encoded_data_test=tokenizer.batch_encode_plus(X_test,
                                               add_special_tokens=True,
                                               return_attention_mask=True,
                                               pad_to_max_length=True,
                                              
                                               max_length=max_len,
                                               return_tensors='pt')

Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (

In [78]:
X_train[1]

'Arithmetic properties of polynomials'

In [105]:
input_ids_train=encoded_data_train['input_ids']                                  #above task returns dictionary having these keys
attention_masks_train=encoded_data_train['attention_mask']                       #input ids have the tensors of tokens of every word
labels_train=torch.tensor(np.asarray(Y_train))                #making tensor of labels

input_ids_val=encoded_data_val['input_ids']
attention_masks_val=encoded_data_val['attention_mask']
labels_val=torch.tensor(np.asarray(Y_val))

input_ids_test=encoded_data_test['input_ids']
attention_masks_test=encoded_data_test['attention_mask']
#labels_val=torch.tensor(np.asarray(Y_val))

TypeError: ignored

In [81]:
labels_train.shape

torch.Size([16777, 24])

In [82]:
dataset_train=TensorDataset(input_ids_train,attention_masks_train,labels_train)   #using tensor dataset
dataset_test=TensorDataset(input_ids_test,attention_masks_test)   #using tensor dataset

dataset_val=TensorDataset(input_ids_val,attention_masks_val,labels_val)

In [83]:
from transformers import BertForSequenceClassification

#Creating Data Loaders

In [84]:
from torch.utils.data import DataLoader, RandomSampler,SequentialSampler

In [85]:
batch_size=4

dataloader_train=DataLoader(dataset_train,sampler=RandomSampler(dataset_train),             #RandomSampler so that model doesn't learn anything based on sequence of inputs
                            batch_size=batch_size)

dataloader_val=DataLoader(dataset_val,sampler=RandomSampler(dataset_val),             #RandomSampler so that model doesn't learn anything based on sequence of inputs
                            batch_size=32)

dataloader_test=DataLoader(dataset_test,sampler=RandomSampler(dataset_test),             #RandomSampler so that model doesn't learn anything based on sequence of inputs
                            batch_size=32)


#Stating the Performance matrics

In [31]:
import numpy as np
from sklearn.metrics import f1_score
import torch.nn

In [32]:
def f1_score_func(preds,labels):
  pred_flat=np.argmax(preds,axis=1).flatten()                   #flatten-collapses any dimention array into 1-D (though originally more or less)
  labels_flat=labels.flatten()

  return f1_score(labels_flat,pred_flat,average="weighted")


In [33]:
def accuracy_per_class(preds,labels):
  label_dict_inverse={v:k for k,v in label_dict.items()}

  pred_flat=np.argmax(preds,axis=1).flatten()                   #flatten-collapses any dimention array into 1-D (though originally more or less)
  labels_flat=np.argmax(labels,axis=1).flatten() 

  for label in np.unique(labels):
    y_pred=pred_flat[labels_flat==label]
    y_true=labels_flat[labels_flat==label]
    print(f"Class: {label_dict_inverse[label]}")
    print(f"Accuracy: {str(len(y_pred[y_pred==label])) +'/' +str(len(y_true))}\n")

#Training the model

In [34]:
from transformers import AdamW, get_linear_schedule_with_warmup

In [94]:
model= BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',                                              #basic form of BERT easy to handle
    num_labels=6,                                       #number of target classes i.e emotions
    output_attentions=False,                                          #output ate each steps-False
    output_hidden_states=False,       
                                  #output of hidden states
                                                                      # the fine tuning step(i.e (i think)  tuning the model 
                                                                      #as per our requirements e.g num labels etc)
)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

#Setting up Optimizer and Scheduler

In [95]:
optimizer=AdamW(model.parameters(),
                lr=2e-5,  #to 5e-5   ,1e-5
                eps=1e-8
)

In [96]:
epochs=5
scheduler=get_linear_schedule_with_warmup(optimizer,
                                          num_warmup_steps=0,
                                          num_training_steps=len(dataloader_train) * epochs
                                          )

In [61]:
import random
from tqdm.notebook import tqdm
seed_val=17
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

In [98]:
device=torch.device('cuda' if torch.cuda.is_available() else "cpu")
model.to(device)

print(device)

cuda


In [99]:
def evaluate(dataloader):
  model.eval()
  loss_val_total=0
  predictions,true_vals=[],[]

  for batch in dataloader:
    batch=tuple(b.to(device) for b in batch)

    inputs= {                                                                    #batch is in the form of dict having keys input ids,att. mask,labels
        'input_ids':     batch[0],
        'attention_mask':batch[1],
        'labels':        batch[2]
    }
    with torch.no_grad():
      output=model(**inputs)

    loss=output[0]
    logits=output[1]
    loss_val_total+=loss.item()

    logits=logits.detach().cpu().numpy()
    label_ids=inputs['labels'].cpu().numpy()

    predictions.append(logits)
    true_vals.append(label_ids)

  loss_val_avg=loss_val_total/len(dataloader)

  predictions=np.concatenate(predictions,axis=0)
  true_vals=np.concatenate(true_vals,axis=0) 

  return loss_val_avg,predictions,true_vals



In [100]:
for epoch in tqdm(range(1,epochs+1)):
  model.train()

  loss_train_total=0

  progress_bar=tqdm(dataloader_train,desc='Epoch {:1d}'.format(epoch),
                    leave=False,disable=False)
  
  for batch in progress_bar:

    model.zero_grad()

    batch=tuple(b.to(device) for b in batch)

    inputs= {
        'input_ids':     batch[0],
        'attention_mask':batch[1],
        'labels':        batch[2]
    }

    output=model(**inputs)

    loss=output[0]
    loss_train_total+=loss.item()
    loss.backward()

    torch.nn.utils.clip_grad_norm_(model.parameters(),1.0)               #clips the gradients to (1.0)  avoid very  small and very large gradients

    optimizer.step()
    scheduler.step()

    progress_bar.set_postfix({'training_loss': '{:.3f}'.format(loss.item()/len(batch))})                 #postfix to display it after epoch progressbar

  torch.save(model.state_dict(),f'/content/BERT_ft_epoch{epoch}.model')

  tqdm.write('\n Epoch {epoch}')
  loss_train_avg=loss_train_total/len(dataloader_train)
  tqdm.write(f'Training Avg Loss: {loss-loss_train_avg}')

  val_loss,predictions,true_vals=evaluate(dataloader_val)
  val_f1=f1_score_func(predictions,true_vals)
  tqdm.write(f'Validation Avg Loss :{val_loss}')
  tqdm.write(f'F1 Score (weighted): {val_f1}')

ValueError: ignored

In [67]:
inputs['labels'].shape

torch.Size([4, 6])

In [ ]:
model