<a href="https://colab.research.google.com/github/vyassuyog1/Janta-hack1/blob/Word-count/JantaHackLibrary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Data

In [1]:
import pandas as pd

In [2]:
!unzip '/content/test_8iecVfC.zip'
!unzip '/content/train_tGmol3O.zip'

Archive:  /content/test_8iecVfC.zip
  inflating: test.csv                
Archive:  /content/train_tGmol3O.zip
  inflating: train.csv               


In [3]:
data_train_original=pd.read_csv('/content/train.csv')
data_test_original=pd.read_csv('/content/test.csv')
data_train=data_train_original.copy()
data_train.set_index(['ID'],inplace=True)
data_test=data_test_original.copy()
data_test.set_index(['ID'],inplace=True)
print(data_train.shape,data_test.shape)
data_train

(20972, 8) (8989, 2)


TITLE  ... Quantitative Finance
ID                                                        ...                     
1            Reconstructing Subject-Specific Effect Maps  ...                    0
2                     Rotation Invariance Neural Network  ...                    0
3      Spherical polyharmonics and Poisson kernels fo...  ...                    0
4      A finite element approximation for the stochas...  ...                    0
5      Comparative study of Discrete Wavelet Transfor...  ...                    0
...                                                  ...  ...                  ...
20968  Contemporary machine learning: a guide for pra...  ...                    0
20969  Uniform diamond coatings on WC-Co hard alloy c...  ...                    0
20970  Analysing Soccer Games with Clustering and Con...  ...                    0
20971  On the Efficient Simulation of the Left-Tail o...  ...                    0
20972   Why optional stopping is a problem for Bayesians  ...                    0

[20972 rows x 8 columns]

In [4]:
data_test

TITLE                                           ABSTRACT
ID                                                                                                         
20973  Closed-form Marginal Likelihood in Gamma-Poiss...    We present novel understandings of the Gamma...
20974  Laboratory mid-IR spectra of equilibrated and ...    Meteorites contain minerals from Solar Syste...
20975         Case For Static AMSDU Aggregation in WLANs    Frame aggregation is a mechanism by which mu...
20976  The $Gaia$-ESO Survey: the inner disk intermed...    Milky Way open clusters are very diverse in ...
20977  Witness-Functions versus Interpretation-Functi...    Proving that a cryptographic protocol is cor...
...                                                  ...                                                ...
29957  Supporting mixed-datatype matrix multiplicatio...    We approach the problem of implementing mixe...
29958        An axiomatic basis for Blackwell optimality    In the theory of Markov decision processes (...
29959  GeneVis - An interactive visualization tool fo...    GeneVis is a web-based tool to visualize com...
29960  Quantifying the causal effect of speed cameras...    This paper quantifies the effect of speed ca...
29961                      Cube-magic labelings of grids    We show that the vertices and edges of a $d$...

[8989 rows x 2 columns]

In [5]:
df=pd.concat([data_train,data_test],axis=0)
df

TITLE  ... Quantitative Finance
ID                                                        ...                     
1            Reconstructing Subject-Specific Effect Maps  ...                  0.0
2                     Rotation Invariance Neural Network  ...                  0.0
3      Spherical polyharmonics and Poisson kernels fo...  ...                  0.0
4      A finite element approximation for the stochas...  ...                  0.0
5      Comparative study of Discrete Wavelet Transfor...  ...                  0.0
...                                                  ...  ...                  ...
29957  Supporting mixed-datatype matrix multiplicatio...  ...                  NaN
29958        An axiomatic basis for Blackwell optimality  ...                  NaN
29959  GeneVis - An interactive visualization tool fo...  ...                  NaN
29960  Quantifying the causal effect of speed cameras...  ...                  NaN
29961                      Cube-magic labelings of grids  ...                  NaN

[29961 rows x 8 columns]

In [6]:
df['train']=[1] * len(data_train) + [0]*len(data_test)
df['train']

ID
1        1
2        1
3        1
4        1
5        1
        ..
29957    0
29958    0
29959    0
29960    0
29961    0
Name: train, Length: 29961, dtype: int64

In [7]:
df

TITLE  ... train
ID                                                        ...      
1            Reconstructing Subject-Specific Effect Maps  ...     1
2                     Rotation Invariance Neural Network  ...     1
3      Spherical polyharmonics and Poisson kernels fo...  ...     1
4      A finite element approximation for the stochas...  ...     1
5      Comparative study of Discrete Wavelet Transfor...  ...     1
...                                                  ...  ...   ...
29957  Supporting mixed-datatype matrix multiplicatio...  ...     0
29958        An axiomatic basis for Blackwell optimality  ...     0
29959  GeneVis - An interactive visualization tool fo...  ...     0
29960  Quantifying the causal effect of speed cameras...  ...     0
29961                      Cube-magic labelings of grids  ...     0

[29961 rows x 9 columns]

#Reading data

In [8]:
df.iloc[10]['ABSTRACT'], df.iloc[10]['TITLE']

('  We present a systematic global sensitivity analysis using the Sobol method\nwhich can be utilized to rank the variables that affect two quantity of\ninterests -- pore pressure depletion and stress change -- around a\nhydraulically-fractured horizontal well based on their degree of importance.\nThese variables include rock properties and stimulation design variables. A\nfully-coupled poroelastic hydraulic fracture model is used to account for pore\npressure and stress changes due to production. To ease the computational cost\nof a simulator, we also provide reduced order models (ROMs), which can be used\nto replace the complex numerical model with a rather simple analytical model,\nfor calculating the pore pressure and stresses at different locations around\nhydraulic fractures. The main findings of this research are: (i) mobility,\nproduction pressure, and fracture half-length are the main contributors to the\nchanges in the quantities of interest. The percentage of the contributio

#Y

In [59]:
import numpy as np


In [60]:
Y=df[df.train==1].iloc[:,2:-1]
Y

Computer Science  Physics  ...  Quantitative Biology  Quantitative Finance
ID                                ...                                            
1                   1.0      0.0  ...                   0.0                   0.0
2                   1.0      0.0  ...                   0.0                   0.0
3                   0.0      0.0  ...                   0.0                   0.0
4                   0.0      0.0  ...                   0.0                   0.0
5                   1.0      0.0  ...                   0.0                   0.0
...                 ...      ...  ...                   ...                   ...
20968               1.0      1.0  ...                   0.0                   0.0
20969               0.0      1.0  ...                   0.0                   0.0
20970               1.0      0.0  ...                   0.0                   0.0
20971               0.0      0.0  ...                   0.0                   0.0
20972               0.0      0.0  ...                   0.0                   0.0

[20972 rows x 6 columns]

In [11]:
Y_max=[np.asarray(np.where(i==1)).flatten() for i in np.asarray(Y)]
Y_max

[array([0]),
 array([0]),
 array([2]),
 array([2]),
 array([0, 3]),
 array([2]),
 array([1]),
 array([1]),
 array([1]),
 array([4]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([2]),
 array([1]),
 array([2]),
 array([3]),
 array([1]),
 array([4]),
 array([1, 2]),
 array([0]),
 array([0]),
 array([2]),
 array([1]),
 array([0]),
 array([2]),
 array([2, 3]),
 array([1, 2]),
 array([0, 3]),
 array([2]),
 array([0]),
 array([4]),
 array([0]),
 array([0, 2]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([3]),
 array([5]),
 array([1]),
 array([0, 2]),
 array([0]),
 array([0]),
 array([2]),
 array([0, 1]),
 array([0]),
 array([3]),
 array([0, 3]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([4]),
 array([1]),
 array([0]),
 array([0, 3]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([3]),
 array([2]),
 array([2]),
 array([0, 3]),
 array([2]),
 array([2, 3]),
 array([1]),
 array([0, 2, 3]),
 array([0

In [12]:
target_dict={k:v for k,v in enumerate(Y.columns)}
target_dict

{0: 'Computer Science',
 1: 'Physics',
 2: 'Mathematics',
 3: 'Statistics',
 4: 'Quantitative Biology',
 5: 'Quantitative Finance'}

#X

In [ ]:
from nltk import stem
stemmer=stem.LancasterStemmer()
stemmer.stem(X_train_val[1])


In [78]:
X_train_val=df[df.train==1]['TITLE'] + df[df.train==1]['ABSTRACT']
X_train_val=[str(i).split() for i in X_train_val]

X_test=df[df.train==0]['TITLE'] + df[df.train==0]['ABSTRACT']
X_test=[str(i).split() for i in X_test]

len(X_test),len(X_train_val)

(8989, 20972)

In [ ]:
X_train_val[1], Y_max[1]

In [142]:
for i in range(len(X_train_val)):
  X_train_val[i]=[stemmer.stem(str(j)) for j in X_train_val[i]]
for k in range(len(X_test)):
  X_test[k]=[stemmer.stem(str(l)) for l in X_test[k]]  


In [143]:
len(X_train_val),len(X_test)

(20972, 8989)

#Classwise word count

In [50]:
from collections import defaultdict
word_count_dict=defaultdict(lambda: 0)
labels_count=defaultdict(lambda: 0)

for i in range(len(X_train_val)):
  sentence=X_train_val[i]
  labels=Y_max[i]
  for l in labels:
    for word in sentence:
      word_count_dict[(word,l)]+=1
      labels_count[l]+=1


In [51]:
len(word_count_dict),len(labels_count)

(281355, 6)

In [52]:
X_train_val[1][0]

'Rotation'

In [53]:
embedding_matrics={}
word_index={}
index=0
for i in range(len(X_train_val)):
  sentence=X_train_val[i]
  for word in sentence:
    if word not in embedding_matrics:
      embedding=[]
      word_index[word]=index
      index+=1
      for l in list(labels_count.keys()):
        count=word_count_dict[(word,l)]
        total=labels_count[l]
        prob=count/total
        embedding.append(prob)
      embedding_matrics[word]=embedding  
        






In [54]:
len(embedding_matrics)

166272

#Split data

In [55]:
from sklearn.model_selection import train_test_split

In [61]:
X_train,X_val,Y_train,Y_val=train_test_split(X_train_val,np.asarray(Y),random_state=42,test_size=0.2)
print(len(X_train),len(X_val),Y_train.shape,Y_val.shape)

16777 4195 (16777, 6) (4195, 6)


#Preprocessing input

In [62]:
from tensorflow.keras.preprocessing.text import Tokenizer 
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [63]:
ov_tok='<OOV>'
EMBEDDING_DIM=6
max_len=max([len(i) for i in X_train_val])
print(max_len)
vocab_size=10000

449


In [64]:
tokenizer=Tokenizer(num_words=vocab_size,oov_token=ov_tok,lower=True,filters=None)
tokenizer.fit_on_texts(X_train_val)

X_train_sequences= tokenizer.texts_to_sequences(X_train)
X_test_sequences= tokenizer.texts_to_sequences(X_test)
X_val_sequences= tokenizer.texts_to_sequences(X_val)

word_index=tokenizer.word_index

X_train_pad=pad_sequences(X_train_sequences, padding="post",truncating='post',maxlen=max_len)
X_val_pad=pad_sequences(X_val_sequences, padding="post",truncating='post',maxlen=max_len)
X_test_pad=pad_sequences(X_test_sequences, padding="post",truncating='post',maxlen=max_len)

In [65]:
vocab_size=len(word_index) + 1
embedding_matrix=np.zeros((vocab_size,EMBEDDING_DIM))

for word,i in (word_index.items()):
  embedding_vector=embedding_matrics.get(word)
  if embedding_vector:
    embedding_matrix[i]=embedding_vector
    
embedding_matrix

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [5.32480172e-02, 6.37692729e-02, 5.49748627e-02, 6.82017505e-02,
        5.28333717e-02, 6.71464884e-02],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.56531267e-06, 1.23464107e-06, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.56531267e-06, 1.23464107e-06, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]])

In [66]:
X_train_padded = np.array(X_train_pad).astype(np.float32)                                #converting to float as tensors need float datatype
X_test_padded = np.array(X_test_pad).astype(np.float32)
X_val_padded = np.array(X_val_pad).astype(np.float32)

Y_train = np.array(Y_train).astype(np.float32)
#Y_test = np.array(Y_test).astype(np.float32)
Y_val = np.array(Y_val).astype(np.float32)

#Model

In [67]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from __future__ import division, print_function
from keras.callbacks import ModelCheckpoint
from keras.layers import Dense, Dropout, BatchNormalization
from keras.models import Sequential
from keras.models import Model

In [68]:
model=tf.keras.Sequential([
                           tf.keras.layers.Embedding(vocab_size,EMBEDDING_DIM,weights=[embedding_matrix],input_length=max_len),
                           tf.keras.layers.GlobalAveragePooling1D(),
                           tf.keras.layers.Dense(64,activation='sigmoid'),
                           tf.keras.layers.Dense(6,activation='sigmoid')
])

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 449, 6)            929370    
_________________________________________________________________
global_average_pooling1d_1 ( (None, 6)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                448       
_________________________________________________________________
dense_3 (Dense)              (None, 6)                 390       
Total params: 930,208
Trainable params: 930,208
Non-trainable params: 0
_________________________________________________________________


In [69]:
checkpoint_filepath = '/content/checkpoint'
model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=True,
    monitor='val_acc',
    mode='max',
    save_best_only=True)

In [70]:

num_epochs=20
batch_size=32

history=model.fit(X_train_padded,
                  Y_train,
                  batch_size,
                  num_epochs,
                  validation_data=(X_val_padded,Y_val),
                  shuffle=True,
                  callbacks=[model_checkpoint_callback]
                  
                  )

Epoch 1/20
525/525 [==============================] - 7s 13ms/step - loss: 1.8775 - acc: 0.4096 - val_loss: 1.8760 - val_acc: 0.4033
Epoch 2/20
525/525 [==============================] - 7s 13ms/step - loss: 1.8417 - acc: 0.4114 - val_loss: 1.8513 - val_acc: 0.4033
Epoch 3/20
525/525 [==============================] - 7s 12ms/step - loss: 1.7524 - acc: 0.4712 - val_loss: 1.6812 - val_acc: 0.5154
Epoch 4/20
525/525 [==============================] - 7s 12ms/step - loss: 1.5123 - acc: 0.6563 - val_loss: 1.3979 - val_acc: 0.7101
Epoch 5/20
525/525 [==============================] - 7s 12ms/step - loss: 1.2761 - acc: 0.7289 - val_loss: 1.2450 - val_acc: 0.7399
Epoch 6/20
525/525 [==============================] - 7s 14ms/step - loss: 1.1711 - acc: 0.7473 - val_loss: 1.1864 - val_acc: 0.7487
Epoch 7/20
525/525 [==============================] - 7s 13ms/step - loss: 1.1198 - acc: 0.7565 - val_loss: 1.1589 - val_acc: 0.7149
Epoch 8/20
525/525 [==============================] - 7s 13ms/step - 

In [72]:
model.load_weights(checkpoint_filepath)

model.evaluate(X_val_padded,Y_val,verbose=2)

132/132 - 0s - loss: 1.1311 - acc: 0.7545


[1.1311044692993164, 0.754469633102417]

In [73]:
Y_pred=model.predict(X_test_padded,32,callbacks=[model_checkpoint_callback])
Y_pred

array([[0.02174547, 0.00253312, 0.00949175, 0.01145   , 0.00098207,
        0.00092403],
       [0.00576738, 0.19198571, 0.00238312, 0.00066725, 0.00283565,
        0.00074878],
       [0.03802824, 0.00172331, 0.00471554, 0.02036462, 0.00145467,
        0.0010671 ],
       ...,
       [0.02419853, 0.0091009 , 0.002576  , 0.00726232, 0.00221167,
        0.00098522],
       [0.07756423, 0.00036178, 0.00483736, 0.0658976 , 0.0013712 ,
        0.00126529],
       [0.01241124, 0.00348139, 0.02015206, 0.00659865, 0.00063933,
        0.00080046]], dtype=float32)

In [74]:
Y=pd.DataFrame(Y_pred,columns=list(df.columns[2:-1]))
Y

Computer Science   Physics  ...  Quantitative Biology  Quantitative Finance
0             0.021745  0.002533  ...              0.000982              0.000924
1             0.005767  0.191986  ...              0.002836              0.000749
2             0.038028  0.001723  ...              0.001455              0.001067
3             0.003986  0.828164  ...              0.009525              0.000764
4             0.020419  0.002547  ...              0.000920              0.000908
...                ...       ...  ...                   ...                   ...
8984          0.025061  0.009258  ...              0.002338              0.001001
8985          0.012394  0.002279  ...              0.000506              0.000791
8986          0.024199  0.009101  ...              0.002212              0.000985
8987          0.077564  0.000362  ...              0.001371              0.001265
8988          0.012411  0.003481  ...              0.000639              0.000800

[8989 rows x 6 columns]

In [75]:
for i in range(len(Y)):
  threshold=Y.iloc[i].mean(axis=0)
  for j in range(Y.shape[1]):
    if (Y.iloc[i][j])<=(threshold):
      Y.iloc[i][j]=0
    else:
      Y.iloc[i][j]=1

Y

Computer Science  Physics  ...  Quantitative Biology  Quantitative Finance
0                  1.0      0.0  ...                   0.0                   0.0
1                  0.0      1.0  ...                   0.0                   0.0
2                  1.0      0.0  ...                   0.0                   0.0
3                  0.0      1.0  ...                   0.0                   0.0
4                  1.0      0.0  ...                   0.0                   0.0
...                ...      ...  ...                   ...                   ...
8984               1.0      1.0  ...                   0.0                   0.0
8985               1.0      0.0  ...                   0.0                   0.0
8986               1.0      1.0  ...                   0.0                   0.0
8987               1.0      0.0  ...                   0.0                   0.0
8988               1.0      0.0  ...                   0.0                   0.0

[8989 rows x 6 columns]

In [76]:
submission=pd.concat([data_test_original.ID,Y],axis=1)
submission.set_index('ID',inplace=True)
submission

Computer Science  Physics  ...  Quantitative Biology  Quantitative Finance
ID                                ...                                            
20973               1.0      0.0  ...                   0.0                   0.0
20974               0.0      1.0  ...                   0.0                   0.0
20975               1.0      0.0  ...                   0.0                   0.0
20976               0.0      1.0  ...                   0.0                   0.0
20977               1.0      0.0  ...                   0.0                   0.0
...                 ...      ...  ...                   ...                   ...
29957               1.0      1.0  ...                   0.0                   0.0
29958               1.0      0.0  ...                   0.0                   0.0
29959               1.0      1.0  ...                   0.0                   0.0
29960               1.0      0.0  ...                   0.0                   0.0
29961               1.0      0.0  ...                   0.0                   0.0

[8989 rows x 6 columns]

In [77]:
submission.to_csv("submissionM.csv")
